name: my_auto_guide
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # Backend
  supabase_flutter: ^2.10.0

  # UI
  dotted_border: ^3.1.0
  photo_view: ^0.14.0

  # Web / contenido
  url_launcher: ^6.2.5
  youtube_player_iframe: ^4.0.4
  webview_flutter: ^4.9.0

  # Archivos
  file_picker: ^8.0.0
  open_filex: ^4.0.0
  path_provider: ^2.0.11

  # Red
  http: ^1.5.0

  # Permisos
  permission_handler: ^12.0.1
  device_info_plus: ^11.5.0

  # Notificaciones
  flutter_local_notifications: ^17.1.2
  timezone: ^0.9.4

  # Imágenes
  image_picker: ^1.1.0
  vision_gallery_saver: ^3.0.0

  # Almacenamiento local
  shared_preferences: ^2.3.2

  # PDF
  syncfusion_flutter_pdfviewer: ^31.1.18

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/logos/
    - assets/motos/
    - assets/carros/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/APK.png